# -*- coding: utf-8 -*-
"""trabajo_3_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O730Alj5ZUAvc1A-qBLN_LMyPcHcWooq
"""

!pip install flask transformers torch pyngrok

from flask import Flask, request, jsonify
from transformers import MarianMTModel, MarianTokenizer
from pyngrok import ngrok

# Crear una instancia de Flask
app = Flask(__name__)

# Cargar el modelo de traducción (en este caso, de inglés a español)
model_name = "Helsinki-NLP/opus-mt-en-es"
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name)

# Endpoint para la traducción
@app.route("/translate", methods=["POST"])
def translate():
    try:
        # Obtener el texto a traducir desde la solicitud JSON
        data = request.get_json()
        text_to_translate = data.get("text")

        if not text_to_translate:
            return jsonify({"error": "No 'text' field in the request"}), 400

        # Traducir el texto utilizando el modelo de Hugging Face
        translated = translate_text(text_to_translate)

        # Devolver la traducción como respuesta JSON
        return jsonify({"translated_text": translated})

    except Exception as e:
        return jsonify({"error": str(e)}), 500

def translate_text(text):
    # Tokenizar el texto
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

    # Realizar la traducción
    translated_tokens = model.generate(**inputs)

    # Decodificar la traducción
    translated_text = tokenizer.decode(translated_tokens[0], skip_special_tokens=True)

    return translated_text

from pyngrok import ngrok

# Configurar el authtoken de ngrok
ngrok.set_auth_token("2uKDrb7dqU5YGhWMf7PSW1mnOhG_33NRammFDj5mvJBCkjWzE")

# Ahora puedes iniciar ngrok sin problemas
public_url = ngrok.connect(5000)
print(f"Flask app is running at {public_url}")

# Exponer la aplicación Flask a través de ngrok
if __name__ == "__main__":
    # Iniciar ngrok para exponer el servidor
    public_url = ngrok.connect(5000)
    print(f"Flask app is running at {public_url}")
    app.run(port=5000)

#curl -X POST http://https://768a-34-72-120-233.ngrok.io/translate \
#     -H "Content-Type: application/json" \
#     -d '{"text": "Hello, how are you?"}'

# Ejecucion en la terminal
